Repository arpit456jain/Cool-Front-End-Templates, pull requests merged in 2021-07, with the labels that each got.

#19 welcome bot added
  .github/config.yml
Labels: good first issue

#39 Mahesh Chaubey
  engineers copied web/images/pic10.jpg
  engineers copied web/images/pic2.jpg
  engineers copied web/images/pic3.png
  engineers copied web/images/pic4.png
  engineers copied web/images/pic5.jpg
  engineers copied web/images/pic6.jpg
  engineers copied web/images/pic7.jpg
  engineers copied web/images/pic8.jpg
  engineers copied web/images/pic9.jpg
  engineers copied web/index.html
  engineers copied web/style.css
Labels: level 3

#59 Subham Kumar Ojha
  Mmm collections/img/mmm.png
  Mmm collections/site_ex.html
  Mmm collections/site_ex_style.css
Labels: level2

#66 fixed issue #56
  Food Ordering/img/footer.jpg
  Food Ordering/index.html
  Food Ordering/style.css
Labels: DCP21, level2

#67 Update stlye_links.json
  style_links.json
Labels: DCP21, level 1

#71 Added Glassmorphic Profile Card
  Glassmorphic Profile Card/index.html
  Glassmorphic Profile Card/styles.css
  style_links.json
Labels: DCP21, level3

#73 Fixed issues number #69
  Gym/css/style for gym.css
  Gym/gym.html
Labels: DCP21, Level2

#76 Added Maroom - Interior Design Landing Page
  Maroom - Interior Design Landing Page/assets/landing-image.jpeg
  Maroom - Interior Design Landing Page/assets/products-1.jpg
  Maroom - Interior Design Landing Page/assets/products-2.jpg
  Maroom - Interior Design Landing Page/assets/products-3.jpg
  Maroom - Interior Design Landing Page/assets/products-4.jpg
  Maroom - Interior Design Landing Page/index.html
  Maroom - Interior Design Landing Page/styles.css
  style_links.json
Labels: DCP21, Level3

#78 Points Table added in readme
  README.md
Labels: DCP21, Level 1

#81 Added Product Review Page
  Product Review Page/css/styles.css
  Product Review Page/images/image-anne.jpg
  Product Review Page/images/image-colton.jpg
  Product Review Page/images/image-irene.jpg
  Product Review Page/index.html
  style_links.json
Labels: DCP21, Level2

#83 Added github pages and code of conduct
  README.md
Labels: DCP21, Level0

#87 Fixed style_links.json bug
  style_links.json
Labels: DCP21, Level2

#89 ADDED GLASSMORPHISM FORM!
  glassmorphism-form/index.html
  glassmorphism-form/style.css
  style_links.json
Labels: DCP21, Level3

#92 Added Social Media Dashboard
  Social Media Dashboard/css/styles.css
  Social Media Dashboard/index.html
  Social Media Dashboard/js/index.js
  style_links.json
Labels: DCP21, Level3

#93 Added hover company images
  online grocery- store/styler.css
Labels: DCP21, Level 1

#94 Corrected the issue template
  .github/ISSUE_TEMPLATE/Bug_Feature_Docs.md
Labels: DCP21, Level0

#98 Added Weather Template
  Weather/images/heavyrain.png
  Weather/main.css
  Weather/weather.html
Labels: DCP21, Level2

#103 Created Food Website Template
  Food Website Template/Contact.jpg
  Food Website Template/amazon.png
  Food Website Template/bg1.jpg
  Food Website Template/css/phone.css
  Food Website Template/css/style.css
  Food Website Template/demo.html
  Food Website Template/facebook.png
  Food Website Template/google.png
  Food Website Template/index.html
  Food Website Template/logo.png
  Food Website Template/microsoft.png
  Food Website Template/pic1.jpg
  Food Website Template/pizza.png
  Food Website Template/skype.png
Labels: DCP21, Level2

#104 Updated Home Page UI
  index.html
  script.js
  style.css
  style_links.json
Labels: DCP21, Level3

#106 Added Preview Images
  Admin Dashboard/preview.png
  Artica/preview.png
  Chinese Restaurant/preview.png
  ComingSoon/preview.png
  Covid-19/preview.png
  Food Ordering/preview.png
  Food Website Template/preview.png
  Game zone/preview.png
  Glassmorphic Profile Card/preview.png
  Maroom - Interior Design Landing Page/preview.png
  Mmm collections/preview.png
  Obatin - Medicine Landing Page/preview.png
  Pizza Corner/preview.png
  Portfolio/preview.png
  Product Review Page/preview.png
  Responsive Imaginative/preview.png
  Simple portfolio template/preview.png
  Social Media Dashboard/preview.png
  Stationary website/preview.png
  Tailwind Portfolio/preview.png
  Technology Page/preview.png
  Tribute Page/preview.png
  We design and develop/preview.png
  Weather/preview.png
  Welcome to lucknow/preview.png
  Yoga template/preview.png
  engineers copied web/preview.png
  glassmorphism-form/preview.png
  online grocery- store/preview.png
  portfolio Avinash/preview.png
  script.js
  style.css
  style_links.json
Labels: DCP21, Level3

#108 Image Render Fix
  style.css
  style_links.json
Labels: DCP21, Level 1

#113 Improve yoga templates(#99)
  Yoga template/icon.png
  Yoga template/img.jpg
  Yoga template/img/aj1.jpg
  Yoga template/index.html
  Yoga template/preview.png
  Yoga template/script.js
  Yoga template/style.css
Labels: DCP21, Level3

#114 Added home page gif
  README.md
Labels: DCP21, Level 1

#115 Added back to top
  index.html
  script.js
  style.css
Labels: DCP21, Level 1

#117 Improve ui design #(100)
  Stationary website/about us.html
  Stationary website/contact us.html
  Stationary website/img/1.jpg
  Stationary website/img/2.jpg
  Stationary website/img/3.jpg
  Stationary website/img/4.jpg
  Stationary website/img/5.jpg
  Stationary website/img/6.jpg
  Stationary website/img/8.jpg
  Stationary website/img/9.jpg
  Stationary website/img/favicon.png
  Stationary website/index.html
  Stationary website/preview.png
  Stationary website/st1.jpg
  Stationary website/st2.jpg
  Stationary website/st3.jpg
Labels: DCP21, Level2

#126 Ankita
  Yoga template/asan.png
  Yoga template/index.html
  Yoga template/service1.png
  Yoga template/service2.png
  Yoga template/service3.png
  Yoga template/service4.png
  Yoga template/style.css
Labels: DCP21, Level2
