Repository arpit456jain/Cool-Front-End-Templates, pull requests merged in 2022-04, with the labels that each got.

#531 Added microsoft clone of teams files
  Microsoft_Teams_Clone/assets/css/bootstrap.css
  Microsoft_Teams_Clone/assets/css/bootstrap.css.map
  Microsoft_Teams_Clone/assets/css/style.css
  Microsoft_Teams_Clone/assets/media/Teams_Icon.jpg
  Microsoft_Teams_Clone/assets/media/person.png
  Microsoft_Teams_Clone/index.html
  Microsoft_Teams_Clone/scripts/bootstrap.bundle.js
  Microsoft_Teams_Clone/scripts/bootstrap.bundle.js.map
Labels: Level2, GSSoC22, ready to merge

#513 added a book website template under issue #497
  Books_Website_Template/css/styles.css
  Books_Website_Template/images/50ShadesofGrey.jpg
  Books_Website_Template/images/Albert Einstein.jpg
  Books_Website_Template/images/Charles W Eliot.jpg
  Books_Website_Template/images/George RR martin.jpeg
  Books_Website_Template/images/Harry-Potter.jpg
  Books_Website_Template/images/House-of-Earth-and-Blood-by-Sarah-J.-Maas.jpg
  Books_Website_Template/images/JK Rowling.jpg
  Books_Website_Template/images/Jane Austin.jpg
  Books_Website_Template/images/Logan Peril Smith.jpg
  Books_Website_Template/images/Oscar Wilde.jpg
  Books_Website_Template/images/Reflections-from-The-Alchemist.jpg
  Books_Website_Template/images/Signs-Youre-Book-Lover.jpg
  Books_Website_Template/images/The Diary of a young girl.jpg
  Books_Website_Template/images/To_Kill_a_Mockingbird.jpg
  Books_Website_Template/images/Voltaire.jpg
  Books_Website_Template/images/favicon.png
  Books_Website_Template/images/from blood and ash.jpg
  Books_Website_Template/images/the salient patient.jpg
  Books_Website_Template/index.html
  Books_Website_Template/preview.png
  style_links.json
Labels: Level2, GSSoC22, ready to merge

#523 Added the new pages
  E commerce shopping website template/aboutus.css
  E commerce shopping website template/aboutus.html
  E commerce shopping website template/contactpage.html
  E commerce shopping website template/images/108-full-sleeve-t-shirts-for-men-1.jpg
  E commerce shopping website template/images/61ecbuT3TnL._UY550_.jpg
  E commerce shopping website template/images/61iY640AIlL._UY550_.jpg
  E commerce shopping website template/images/Google-Play-Icon3.jpg
  E commerce shopping website template/images/Guide-mens-smart-casual-dress-code4.jpg
  E commerce shopping website template/images/apple store.jpg
  E commerce shopping website template/images/apple watch.jpg
  E commerce shopping website template/images/apple.png
  E commerce shopping website template/images/bag icon.png
  E commerce shopping website template/images/baseball jacket.jpg
  E commerce shopping website template/images/belt 2.jpg
  E commerce shopping website template/images/belt.jpg
  E commerce shopping website template/images/belts.jpg
  E commerce shopping website template/images/blue-print-turquoise-men-s-shirt.jpg
  E commerce shopping website template/images/cap.jpg
  E commerce shopping website template/images/cocacola2.png
  E commerce shopping website template/images/download.jpg
  E commerce shopping website template/images/fashion 1.jpeg
  E commerce shopping website template/images/formal shoes.jpg
  E commerce shopping website template/images/formal-attire-18-4.jpg
  E commerce shopping website template/images/girl2.png
  E commerce shopping website template/images/godrej.png
  E commerce shopping website template/images/leather-jacket-tan-edinburgh-p234-1052_zoom.jpg
  E commerce shopping website template/images/man 1.jpg
  E commerce shopping website template/images/man2.jpg
  E commerce shopping website template/images/men watch.jpeg
  E commerce shopping website template/images/men's cap 2.jpg
  E commerce shopping website template/images/men-s-cotton-shirt-500x500.jpg
  E commerce shopping website template/images/men-sweatshirt-250x250.jpg
  E commerce shopping website template/images/menu 2.png
  E commerce shopping website template/images/mylogo1.png
  E commerce shopping website template/images/oppo.png
  E commerce shopping website template/images/paypal.png
  E commerce shopping website template/images/printed tshirt new.jpg
  E commerce shopping website template/images/samsung.png
  E commerce shopping website template/images/shirt -0.jpg
  E commerce shopping website template/images/shoes red.jpg
  E commerce shopping website template/images/shoes.jpg
  E commerce shopping website template/images/shoes2.jpg
  E commerce shopping website template/images/socks.jpg
  E commerce shopping website template/images/sport.jpg
  E commerce shopping website template/images/stylish watch.webp
  E commerce shopping website template/images/watch -----.jpg
  E commerce shopping website template/images/watch 2.jpg
  E commerce shopping website template/images/watch black.jpeg
  E commerce shopping website template/index.html
  E commerce shopping website template/infinity.png
  E commerce shopping website template/products.html
  E commerce shopping website template/profile.html
Labels: Level1, GSSoC22, ready to merge

#527 #504 fixed- Added responsive contact page and about page
  Apple Webiste UI Clone/style.css
  Home design/about.css
  Home design/about.html
  Home design/contact.html
  Home design/contact_page.css
  Home design/css/style.css
  Home design/images/contact.jpg
  Home design/index.html
Labels: Level2, GSSoC22, ready to merge

#548 Hotel website
  Hotel Website/Preview.png
  Hotel Website/clean.css
  Hotel Website/images/DELHI.jpg
  Hotel Website/images/Goa.jpg
  Hotel Website/images/Udaipur.jpg
  Hotel Website/images/cancel-icici-bank-credit-card.webp
  Hotel Website/images/del hotel.jpg
  Hotel Website/images/fifty.png
  Hotel Website/images/icici.png
  Hotel Website/images/img.jpg
  Hotel Website/images/jaipur.jpg
  Hotel Website/images/luxury.jpg
  Hotel Website/images/makemytrip_425_735_425_735.jpg
  Hotel Website/images/the-park-new-delhi.jpg
  Hotel Website/index.html
Labels: Level2, GSSoC22, ready to merge

#573 Making the food template fully responsive
  Food_Template/index.html
  Food_Template/style.css
Labels: Level2

#570 New Interface For the website
  index.html
  reactlogo.png
  script.js
  style.css
Labels: Level1

#540 Contact us added
  Technology Page/index.html
  Technology Page/style.css
Labels: Level1, GSSoC22

#575 Improved Chinese Resturant
  Chinese Restaurant/img/1.jpg
  Chinese Restaurant/img/10.jpg
  Chinese Restaurant/img/11.jpg
  Chinese Restaurant/img/1st.jpg
  Chinese Restaurant/img/2.jpg
  Chinese Restaurant/img/3.jpg
  Chinese Restaurant/img/4.jpg
  Chinese Restaurant/img/5.jpg
  Chinese Restaurant/img/6.jpg
  Chinese Restaurant/img/7.jpg
  Chinese Restaurant/img/8.jpg
  Chinese Restaurant/img/9.jpg
  Chinese Restaurant/img/amb.jpg
  Chinese Restaurant/img/bg.jpg
  Chinese Restaurant/img/cater1.png
  Chinese Restaurant/img/chow.jpg
  Chinese Restaurant/img/circle-cropped (1).png
  Chinese Restaurant/img/circle-cropped (2).png
  Chinese Restaurant/img/circle-cropped (3).png
  Chinese Restaurant/img/circle-cropped (4).png
  Chinese Restaurant/img/circle-cropped (5).png
  Chinese Restaurant/img/circle-cropped (6).png
  Chinese Restaurant/img/dumpling.jpg
  Chinese Restaurant/img/fried.jpg
  Chinese Restaurant/img/hygine.jpg
  Chinese Restaurant/img/img.jpg
  Chinese Restaurant/img/img2.jpg
  Chinese Restaurant/img/logo.png
  Chinese Restaurant/img/music.png
  Chinese Restaurant/img/pasta.jpg
  Chinese Restaurant/img/pic.jpeg
  Chinese Restaurant/img/pizza.jpg
  Chinese Restaurant/img/platter.jpg
  Chinese Restaurant/img/rolls.webp
  Chinese Restaurant/img/spag.jpg
  Chinese Restaurant/img/sushi-place.jpg
  Chinese Restaurant/img/wait.jpg
  Chinese Restaurant/img/wifi.jpg
  Chinese Restaurant/index.html
  Chinese Restaurant/style.css
Labels: Level2, GSSoC22, ready to merge

#545 Template for Notes providing Website
  MedEasy Website/images/anatomy.png
  MedEasy Website/images/logo.png
  MedEasy Website/images/main.png
  MedEasy Website/images/ophthalmalogy.png
  MedEasy Website/images/pharmacology.png
  MedEasy Website/images/physiology.png
  MedEasy Website/index.html
  MedEasy Website/js/script.js
  MedEasy Website/preview.png
  MedEasy Website/styles/styles.css
  style_links.json
Labels: Level2, GSSoC22, ready to merge

#560 #533 Wikipedia Clone created
  Portfolio Template/index.html
  Wikipedia-Clone/CSS/app.css
  Wikipedia-Clone/CSS/bootstrap.min.css
  Wikipedia-Clone/CSS/download.css
  Wikipedia-Clone/CSS/footer.css
  Wikipedia-Clone/CSS/idiom.css
  Wikipedia-Clone/CSS/language.css
  Wikipedia-Clone/CSS/line.css
  Wikipedia-Clone/CSS/logo.css
  Wikipedia-Clone/CSS/main-footer.css
  Wikipedia-Clone/CSS/media.css
  Wikipedia-Clone/CSS/search.css
  Wikipedia-Clone/CSS/styles.css
  Wikipedia-Clone/CSS/wiki.css
  Wikipedia-Clone/CSS/wikimedia.css
  Wikipedia-Clone/ICON/wikipedia.ico
  Wikipedia-Clone/LICENSE
  Wikipedia-Clone/README.md
  Wikipedia-Clone/SVG/Commons-logo_sister.svg
  Wikipedia-Clone/SVG/MediaWiki-logo_sister.svg
  Wikipedia-Clone/SVG/Meta-Wiki-logo_sister.svg
  Wikipedia-Clone/SVG/Wikibooks-logo_sister.svg
  Wikipedia-Clone/SVG/Wikidata-logo_sister.svg
  Wikipedia-Clone/SVG/Wikimedia-logo_black.svg
  Wikipedia-Clone/SVG/Wikipedia-logo-v2.svg
  Wikipedia-Clone/SVG/Wikiquote-logo_sister.svg
  Wikipedia-Clone/SVG/Wikisource-logo_sister.svg
  Wikipedia-Clone/SVG/Wikispecies-logo_sister.svg
  Wikipedia-Clone/SVG/Wikiversity-logo_sister.svg
  Wikipedia-Clone/SVG/Wikivoyage-logo_sister.svg
  Wikipedia-Clone/SVG/Wiktionary-logo_sister.svg
  Wikipedia-Clone/SVG/arrow-down-blue.svg
  Wikipedia-Clone/SVG/badge_google_play_store.svg
  Wikipedia-Clone/SVG/badge_ios_app_store.svg
  Wikipedia-Clone/SVG/language-icon.svg
  Wikipedia-Clone/SVG/wikipedia_app_tile.svg
  Wikipedia-Clone/img/ScreenShot.png
  Wikipedia-Clone/img/wikipedia.png
  Wikipedia-Clone/index.html
  Wikipedia-Clone/package-lock.json
  Wikipedia-Clone/package.json
Labels: question, GSSoC22

#599 Updated readme
  README.md
Labels: Level1

#589 COnfigured the bot
  .github/workflows/pr-labeler.yml
Labels: Urgent, GSSoC22, Level0

#596 New UI for coming soon created
  ComingSoon/assets/css/style.css
  ComingSoon/assets/js/main.js
  ComingSoon/img/happy-student-animate.svg
  ComingSoon/index.html
Labels: Level2

#593 added newsletter title and fixed cutout text for newsletter project
  Newsletter/index.html
  Newsletter/style.css
Labels: Level0

#605 fixed responsiveness fully and added title for rural art project
  Rural Art Template/index.css
  Rural Art Template/index.html
Labels: Level2, GSSoC22, ready to merge

#568 Added a landing page
  Landing_Page/Code/index.js
  Landing_Page/Code/style.css
  Landing_Page/assets/251.svg
  Landing_Page/assets/dextopView.png
  Landing_Page/assets/mobileView.png
  Landing_Page/index.html
  style_links.json
Labels: Level2, GSSoC22, ready to merge

#583 changed the design of footer along with background image
  Maroom - Interior Design Landing Page/2.jpg
  Maroom - Interior Design Landing Page/index.html
  Maroom - Interior Design Landing Page/social.png
  Maroom - Interior Design Landing Page/style.css
  Maroom - Interior Design Landing Page/styles.css
Labels: GSSoC22, ready to merge

#612 Improved stationery website
  Stationary website/about us.html
  Stationary website/contact us.html
  Stationary website/img/1.jpg
  Stationary website/img/2.jpg
  Stationary website/img/3.jpg
  Stationary website/img/4.jpg
  Stationary website/img/5.jpg
  Stationary website/img/6.jpg
  Stationary website/img/9.jpg
  Stationary website/img/card.png
  Stationary website/img/clip.jpg
  Stationary website/img/cray2.jpg
  Stationary website/img/dura.jpg
  Stationary website/img/gift2.jpeg
  Stationary website/img/good.jpg
  Stationary website/img/graph.jpg
  Stationary website/img/img1.jpg
  Stationary website/img/img2.jpg
  Stationary website/img/img4.jpg
  Stationary website/img/lock4.png
  Stationary website/img/note3.jpg
  Stationary website/img/o.jpg
  Stationary website/img/pen.jpeg
  Stationary website/img/pen3.jpg
  Stationary website/img/pencil.jpeg
  Stationary website/img/plane.jpg
  Stationary website/img/return.jpg
  Stationary website/index.html
  Stationary website/style.css
Labels: Level2, GSSoC22, ready to merge

#614 Fix the button issue and hover effect is added + smooth scrolling
  Tailwind Portfolio/css/mystyle.css
  Tailwind Portfolio/index.html
Labels: Level1, GSSoC22, ready to merge

#590 Making the admin panel fully responsive
  Admin Dashboard/css/style.css
  Admin Dashboard/index.html
Labels: Level2, GSSoC22

#609 tourism responsive website added
  Tourism_Responsive_Website/images/Amritsar.jpg
  Tourism_Responsive_Website/images/Rajgad-Fort.jpg
  Tourism_Responsive_Website/images/Sealink.jpg
  Tourism_Responsive_Website/images/Tajmahal.jpg
  Tourism_Responsive_Website/images/agra-fort.jpg
  Tourism_Responsive_Website/images/banner.jpg
  Tourism_Responsive_Website/images/beach_road.jpg
  Tourism_Responsive_Website/images/ellora-caves.jpg
  Tourism_Responsive_Website/images/gateway-india.jpg
  Tourism_Responsive_Website/images/harmandir-sahib.jpg
  Tourism_Responsive_Website/images/jaisalmer.jpg
  Tourism_Responsive_Website/images/logo.jpg
  Tourism_Responsive_Website/images/logo1.jpg
  Tourism_Responsive_Website/images/mahabodhi-temple.jpg
  Tourism_Responsive_Website/images/mecca-masjid.jpg
  Tourism_Responsive_Website/images/mine.jpeg
  Tourism_Responsive_Website/images/mysore-palace.jpg
  Tourism_Responsive_Website/images/red-fort.jpg
  Tourism_Responsive_Website/images/user1.jpg
  Tourism_Responsive_Website/images/user2.jpg
  Tourism_Responsive_Website/images/user3.jpg
  Tourism_Responsive_Website/images/varanasi.jpg
  Tourism_Responsive_Website/index.html
  Tourism_Responsive_Website/preview.png
  Tourism_Responsive_Website/style.css
  style_links.json
Labels: GSSoC22, changes requested

#613 Service section template
  Service Section Template/Readme
  Service Section Template/index.html
  Service Section Template/style.css
Labels: Level1, GSSoC22

#635 Updating the README.md file with important links
  README.md
Labels: Level1, GSSoC22, ready to merge

#648 open projects in new tab and deleted repeated projects
  script.js
  style_links.json
Labels: Level1, GSSoC22

#627 I have added a background color so it will look good and give user an…
  E commerce shopping website template/STYLE/clean.css
Labels: GSSoC22, Level0

#626 Updated Medeasy notes website template
  MedEasy Website/images/about.png
  MedEasy Website/images/contactus.png
  MedEasy Website/index.html
  MedEasy Website/preview images/about.png
  MedEasy Website/preview images/contactus.png
  MedEasy Website/preview images/contribute.png
  MedEasy Website/preview images/home.png
  MedEasy Website/preview images/services.png
  MedEasy Website/styles/styles.css
  style_links.json
Labels: Level2, GSSoC22

#632 added missing display images and fixed image styles
  AnimatedFrontendWebsite/preview.png
  Landing_Page/preview.png
  Weather/index.html
  style.css
  style_links.json
Labels: Level1, GSSoC22

#643 changed opacity of navbar
  Yoga Template 2/style.css
Labels: GSSoC22, Level0

#637 changed UI of the service section and added bottom navbar.
  Simple portfolio template/img/fb.png
  Simple portfolio template/img/git.png
  Simple portfolio template/img/insta.png
  Simple portfolio template/img/linked.png
  Simple portfolio template/index.html
  Simple portfolio template/social5.png
  Simple portfolio template/style.css
  Simple portfolio template/style2.css
Labels: Level1, GSSoC22

#638 Added Travel blog + Navbar Hover effect + Document Title
  Welcome to lucknow/blog.html
  Welcome to lucknow/blogstyle.css
  Welcome to lucknow/index.html
  Welcome to lucknow/style.css
Labels: Level2, GSSoC22

#660 modified yoga template 2
  Yoga Template 2/style.css
Labels: GSSoC22, Level0

#646 Added Organic Retail Website Template
  Organic Retail Website Template/README.md
  Organic Retail Website Template/app.js
  Organic Retail Website Template/index.html
  Organic Retail Website Template/preview.png
  Organic Retail Website Template/styles.css
  style_links.json
Labels: GSSoC22

#664 made template responsive and enhanced the UI of service section
  food website template/css/phone.css
  food website template/css/style.css
  food website template/demo.html
  food website template/img/Contact.jpg
  food website template/img/Food Delivery 4.jpg
  food website template/img/amazon.png
  food website template/img/bg1.jpg
  food website template/img/combo.jpeg
  food website template/img/combo4.png
  food website template/img/facebook.png
  food website template/img/google.png
  food website template/img/logo.png
  food website template/img/microsoft.png
  food website template/img/pic1.jpg
  food website template/img/pizza.png
  food website template/img/scooter.png
  food website template/img/skype.png
  food website template/index.html
  food website template/preview.png
Labels: Level2, GSSoC22

#669 Changes Made To Welcome To Lucknow Project
  Welcome to lucknow/City-14.jpg
  Welcome to lucknow/index.html
  Welcome to lucknow/script.js
  index.html
  style.css
Labels: Level3, GSSoC22

#670 Fixed bottom up top button
  Gym Website/index.html
  Gym Website/script.js
  Gym Website/style.css
Labels: Level1, GSSoC22

#687 Removed the entries from json file
  style_links.json
Labels: Level1, GSSoC22

#674 fixed extra space and centered the template , displayed a templates in tablet view...
  index.html
  style.css
Labels: Level1, GSSoC22

#695 New UI for Technology Project
  Technology Page/images/Tech.svg
  Technology Page/images/apple.png
  Technology Page/images/cisco.png
  Technology Page/images/googel.png
  Technology Page/images/logo.png
  Technology Page/images/microsoft.png
  Technology Page/index.html
  Technology Page/style.css
Labels: GSSoC22, ready to merge

#703 New Interface for Guardian Gym
  Gym Website/img/gym-video.mp4
  Gym Website/img/line-dec.png
  Gym Website/img/undraw_healthy_habit_bh-5-w.svg
  Gym Website/index.html
  Gym Website/script.js
  Gym Website/style.css
Labels: GSSoC22, ready to merge

#680 Added Adobe Photo Shop Website Clone
  Adobe PhotoShop Clone Website Clone/Official Adobe Photoshop _ Photo and design software_files/464526.gif
  Adobe PhotoShop Clone Website Clone/Official Adobe Photoshop _ Photo and design software_files/6506.6287db18.css
  Adobe PhotoShop Clone Website Clone/Official Adobe Photoshop _ Photo and design software_files/AdobeMessagingClient.css
  Adobe PhotoShop Clone Website Clone/Official Adobe Photoshop _ Photo and design software_files/Adobe_Corporate_Horizontal_Red_HEX.svg
  Adobe PhotoShop Clone Website Clone/Official Adobe Photoshop _ Photo and design software_files/TC-4708-1.gif
  Adobe PhotoShop Clone Website Clone/Official Adobe Photoshop _ Photo and design software_files/adchoices-small.svg
  Adobe PhotoShop Clone Website Clone/Official Adobe Photoshop _ Photo and design software_files/ai_appicon_64_grayscale.svg
  Adobe PhotoShop Clone Website Clone/Official Adobe Photoshop _ Photo and design software_files/app.1513b24.css
  Adobe PhotoShop Clone Website Clone/Official Adobe Photoshop _ Photo and design software_files/consonantcardcollection.fp-747904224e35126170177c27f75eb26e.css
  Adobe PhotoShop Clone Website Clone/Official Adobe Photoshop _ Photo and design software_files/creative-cloud.svg
  Adobe PhotoShop Clone Website Clone/Official Adobe Photoshop _ Photo and design software_files/d4b2057e.cb098d7c.css
  Adobe PhotoShop Clone Website Clone/Official Adobe Photoshop _ Photo and design software_files/feds.css
  Adobe PhotoShop Clone Website Clone/Official Adobe Photoshop _ Photo and design software_files/home_icon.svg
  Adobe PhotoShop Clone Website Clone/Official Adobe Photoshop _ Photo and design software_files/nil6fkt.css
  Adobe PhotoShop Clone Website Clone/Official Adobe Photoshop _ Photo and design software_files/photoshop-localnav.css
  Adobe PhotoShop Clone Website Clone/Official Adobe Photoshop _ Photo and design software_files/photoshop-mobile.svg
  Adobe PhotoShop Clone Website Clone/Official Adobe Photoshop _ Photo and design software_files/photoshop.html_sdid=SGDJMMG3&mv=search&ef_id=__G_s&s_kwcid=AL!3085!3!444587836949!e!!g!!adobephotoshop!221441708!17534753348&gclid=_
  Adobe PhotoShop Clone Website Clone/Official Adobe Photoshop _ Photo and design software_files/ps_appicon.svg
  Adobe PhotoShop Clone Website Clone/Official Adobe Photoshop _ Photo and design software_files/ps_appicon_64_grayscale.svg
  Adobe PhotoShop Clone Website Clone/Official Adobe Photoshop _ Photo and design software_files/publish.combined.fp-ed165fe183fafc561ad51b93ae0d4dbf.css
  Adobe PhotoShop Clone Website Clone/Official Adobe Photoshop _ Photo and design software_files/react.fp-b6ce1ea1f358e7757c10dbe13faa0192.css
  Adobe PhotoShop Clone Website Clone/Official Adobe Photoshop _ Photo and design software_files/reader_appicon_64_grayscale.svg
  Adobe PhotoShop Clone Website Clone/Official Adobe Photoshop _ Photo and design software_files/social-icon-facebook.svg
  Adobe PhotoShop Clone Website Clone/Official Adobe Photoshop _ Photo and design software_files/social-icon-instagram.svg
  Adobe PhotoShop Clone Website Clone/Official Adobe Photoshop _ Photo and design software_files/social-icon-linkedin.svg
  Adobe PhotoShop Clone Website Clone/Official Adobe Photoshop _ Photo and design software_files/social-icon-twitter.svg
  Adobe PhotoShop Clone Website Clone/Official Adobe Photoshop _ Photo and design software_files/styles.40092c95.css
  Adobe PhotoShop Clone Website Clone/Official Adobe Photoshop _ Photo and design software_files/themethree.fp-e30aaaefe0bf96d3bf6b92de211a2d99.css
  Adobe PhotoShop Clone Website Clone/Official Adobe Photoshop _ Photo and design software_files/vendors.app.1513b24.css
  Adobe PhotoShop Clone Website Clone/Official Adobe Photoshop _ Photo and design software_files/wUniversal.aspx
  Adobe PhotoShop Clone Website Clone/index.html
  Adobe PhotoShop Clone Website Clone/readme
  style_links.json
Labels: Level3, GSSoC22
