Repository arpit456jain/Cool-Front-End-Templates, pull requests merged in 2022-03, with the labels that each got.

#252 PR for netflix clone
  Apple Webiste UI Clone/applepreview.png
  Apple Webiste UI Clone/preview.png
  netflixclone/13 reasons why.png
  netflixclone/Andhadhun.png
  netflixclone/Gangsofwasepur.png
  netflixclone/Gunjan Saxena.png
  netflixclone/Houseofsecrets.png
  netflixclone/Jessicajones.png
  netflixclone/Kotafactory N.png
  netflixclone/Mimi.png
  netflixclone/MismatchedN.png
  netflixclone/Movie.png
  netflixclone/Movie2.png
  netflixclone/Movie3.png
  netflixclone/Panipat.png
  netflixclone/Popularmovie.png
  netflixclone/Popumovie.png
  netflixclone/Preview.png.png
  netflixclone/Queen's gambit.png
  netflixclone/Queereye.png
  netflixclone/Screenshot 2022-02-11 150139.png
  netflixclone/Sooryavanshi.png
  netflixclone/Stepup2.png
  netflixclone/Thalaivi.png
  netflixclone/The Cage.png
  netflixclone/The ranch.png
  netflixclone/Theskyispink.png
  netflixclone/bad boys.png
  netflixclone/cooking.png
  netflixclone/covenan.png
  netflixclone/cursed.png
  netflixclone/delhi crime.png
  netflixclone/flash.png
  netflixclone/index.html
  netflixclone/kissingbooth.png
  netflixclone/legends.png
  netflixclone/ludo.png
  netflixclone/lupin.png
  netflixclone/malang.png
  netflixclone/moneyhiestN.png
  netflixclone/netflix.css
  netflixclone/new girl.png
  netflixclone/paglait.png
  netflixclone/sacred games.png
  netflixclone/shooter.png
  netflixclone/wanted.png
  style_links.json
Labels: Level3, GSSoC22, ready to merge

#268 NEOMORPHIC PORTFOLIO
  Neomorphic Portfolio/css/style.css
  Neomorphic Portfolio/index.html
  Neomorphic Portfolio/js/script.js
Labels: Level3, GSSoC22, ready to merge

#246 Gym Website Template added
  gymWebsite/images/Gym-image-2.jpg
  gymWebsite/images/Gym-image-3.jpg
  gymWebsite/images/backimage.jpg
  gymWebsite/images/backimage1.jpg
  gymWebsite/images/email.png
  gymWebsite/images/ex1.jpg
  gymWebsite/images/facebook.png
  gymWebsite/images/gym-image.jpg
  gymWebsite/images/gymm.jpg
  gymWebsite/images/gymw.jpeg
  gymWebsite/images/img3.jpg
  gymWebsite/images/instagram.png
  gymWebsite/images/logo.jpg
  gymWebsite/images/phone-call.png
  gymWebsite/index.html
  gymWebsite/preview.png
  gymWebsite/style.css
  style_links.json
Labels: Level1, GSSoC22, changes requested

#270 Starbucks Frontend UI Template
  Portfolio Template/CSS/style.css
  Portfolio Template/CSS/styles.css
  Portfolio Template/IMAGES/joanna-kosinska-unsplash.jpg
  Portfolio Template/IMAGES/project-courses.jpg
  Portfolio Template/IMAGES/project-wire-ipsum.jpg
  Portfolio Template/IMAGES/project-women-tech.jpg
  Portfolio Template/index.html
  Starbucks Template/img/box-b.png
  Starbucks Template/img/box-c.png
  Starbucks Template/img/box-d.png
  Starbucks Template/img/box-e.jpg
  Starbucks Template/img/box-f1.jpg
  Starbucks Template/img/box-f2.jpg
  Starbucks Template/img/logo.svg
  Starbucks Template/img/marker.svg
  Starbucks Template/img/social-facebook.svg
  Starbucks Template/img/social-instagram.svg
  Starbucks Template/img/social-pinterest.svg
  Starbucks Template/img/social-spotify.svg
  Starbucks Template/img/social-twitter.svg
  Starbucks Template/img/social-youtube.svg
  Starbucks Template/index.html
  Starbucks Template/readme.md
  Starbucks Template/script.js
  Starbucks Template/style.css
Labels: Level2, GSSoC22

#273 Added WhatsApp
  Whatsapp/README.md
  Whatsapp/img1.jpg
  Whatsapp/img2.jpg
  Whatsapp/index.html
  Whatsapp/pattern.png
  Whatsapp/style.css
  Whatsapp/user.jpg
Labels: Level1, GSSoC22, ready to merge

#282 Space Agency Template Issue Number: #203
  Space Agency Template/css/style.css
  Space Agency Template/css/utilities.css
  Space Agency Template/css/variables.css
  Space Agency Template/img/astronaut.png
  Space Agency Template/img/bus.png
  Space Agency Template/img/engines.png
  Space Agency Template/img/logo.png
  Space Agency Template/img/rocket1.png
  Space Agency Template/img/rocket2.png
  Space Agency Template/img/rocket3.png
  Space Agency Template/img/search.png
  Space Agency Template/img/sunrise.jpg
  Space Agency Template/index.html
  Space Agency Template/js/app.js
Labels: Level2, GSSoC22, ready to merge

#283 Added e commerce shopping website template.
  E commerce shopping website template/STYLE/clean.css
  E commerce shopping website template/contactpage.html
  E commerce shopping website template/images/108-full-sleeve-t-shirts-for-men-1.jpg
  E commerce shopping website template/images/61ecbuT3TnL._UY550_.jpg
  E commerce shopping website template/images/61iY640AIlL._UY550_.jpg
  E commerce shopping website template/images/Google-Play-Icon3.jpg
  E commerce shopping website template/images/Guide-mens-smart-casual-dress-code4.jpg
  E commerce shopping website template/images/apple store.jpg
  E commerce shopping website template/images/apple watch.jpg
  E commerce shopping website template/images/apple.png
  E commerce shopping website template/images/bag icon.png
  E commerce shopping website template/images/belt.jpg
  E commerce shopping website template/images/cocacola2.png
  E commerce shopping website template/images/download.jpg
  E commerce shopping website template/images/fashion 1.jpeg
  E commerce shopping website template/images/formal shoes.jpg
  E commerce shopping website template/images/formal-attire-18-4.jpg
  E commerce shopping website template/images/girl2.png
  E commerce shopping website template/images/godrej.png
  E commerce shopping website template/images/man 1.jpg
  E commerce shopping website template/images/man2.jpg
  E commerce shopping website template/images/men-sweatshirt-250x250.jpg
  E commerce shopping website template/images/menu 2.png
  E commerce shopping website template/images/mylogo1.png
  E commerce shopping website template/images/oppo.png
  E commerce shopping website template/images/paypal.png
  E commerce shopping website template/images/printed tshirt new.jpg
  E commerce shopping website template/images/samsung.png
  E commerce shopping website template/images/shoes.jpg
  E commerce shopping website template/images/shoes2.jpg
  E commerce shopping website template/images/socks.jpg
  E commerce shopping website template/images/watch 2.jpg
  E commerce shopping website template/images/watch black.jpeg
  E commerce shopping website template/index.html
  style_links.json
Labels: Level1, GSSoC22, ready to merge

#300 Photo Gallery Website
  photo gallery/images/image1.jpeg
  photo gallery/images/image10.jpeg
  photo gallery/images/image2.jpeg
  photo gallery/images/image3.jpeg
  photo gallery/images/image4.jpeg
  photo gallery/images/image5.jpeg
  photo gallery/images/image6.jpeg
  photo gallery/images/image7.jpeg
  photo gallery/images/image8.jpeg
  photo gallery/images/image9.jpeg
  photo gallery/index.html
  photo gallery/index.js
  photo gallery/style.css
Labels: GSSoC22

#304 fixed: #236 Weather UI is fully enhanced
  Weather/images/Timeline-1.png
  Weather/images/Timeline-2.png
  Weather/images/Timeline-3.png
  Weather/images/Timeline-4.png
  Weather/images/cloud.png
  Weather/images/humidity.png
  Weather/images/map.png
  Weather/images/rain.png
  Weather/images/rainy-day.png
  Weather/images/search.png
  Weather/images/searchpng.png
  Weather/images/wind.png
  Weather/main.css
  Weather/preview.png
  Weather/weather.html
Labels: Level2

#306 Priyanshu
  Moninfo/Images/indian-monuments.png
  Moninfo/favicon/favicon.ico
  Moninfo/index.html
  Moninfo/preview.png
  Moninfo/styles.css
  style_links.json
Labels: Level2

#259 :memo: updated readme
  README.md
Labels: GSSoC22, ready to merge

#278 Responsive Website Template for a Restaurant. #201
  Restaurant_Template/bg.jpg
  Restaurant_Template/bg2.jpg
  Restaurant_Template/bg3.jpeg
  Restaurant_Template/burger.jpeg
  Restaurant_Template/demo/WhatsApp Image 2022-03-02 at 10.24.09 PM.jpeg
  Restaurant_Template/demo/WhatsApp Image 2022-03-02 at 10.24.34 PM.jpeg
  Restaurant_Template/demo/WhatsApp Image 2022-03-02 at 10.25.04 PM.jpeg
  Restaurant_Template/demo/WhatsApp Image 2022-03-02 at 6.12.32 PM.jpeg
  Restaurant_Template/demo/WhatsApp Image 2022-03-02 at 6.13.15 PM.jpeg
  Restaurant_Template/demo/WhatsApp Image 2022-03-02 at 6.14.01 PM.jpeg
  Restaurant_Template/demo/WhatsApp Image 2022-03-02 at 6.14.28 PM.jpeg
  Restaurant_Template/expert1.jpg
  Restaurant_Template/expert2.jpg
  Restaurant_Template/expert3.jpg
  Restaurant_Template/expert4.jpg
  Restaurant_Template/food.css
  Restaurant_Template/food.html
  Restaurant_Template/menu1.jpeg
  Restaurant_Template/menu2.jpg
  Restaurant_Template/menu3.jpeg
  Restaurant_Template/menu4.jpg
  Restaurant_Template/menu6.jpg
  Restaurant_Template/pasta.jpeg
  Restaurant_Template/sweet.jpeg
Labels: Level2, GSSoC22, changes requested

#314 Microsoft Clone Added
  Microsoft-Clone/assets/banner.png
  Microsoft-Clone/assets/card-5.png
  Microsoft-Clone/assets/card-6.png
  Microsoft-Clone/assets/card1.png
  Microsoft-Clone/assets/card2.png
  Microsoft-Clone/assets/card3.png
  Microsoft-Clone/assets/card4.png
  Microsoft-Clone/assets/card7.png
  Microsoft-Clone/assets/card8.png
  Microsoft-Clone/assets/header.jpg
  Microsoft-Clone/assets/hero-sm.png
  Microsoft-Clone/assets/img1.png
  Microsoft-Clone/assets/img2.png
  Microsoft-Clone/assets/img3.png
  Microsoft-Clone/assets/logo.png
  Microsoft-Clone/assets/signin.svg
  Microsoft-Clone/index.html
  Microsoft-Clone/style.css
Labels: Level3, GSSoC22, ready to merge

#320 Added Online Tutorial Website Template
  Online Tutorial Website Template/Images/delete.html
  Online Tutorial Website Template/Images/right arrow.png
  Online Tutorial Website Template/Images/search.png
  Online Tutorial Website Template/Images/tick.png
  Online Tutorial Website Template/Preview.PNG
  Online Tutorial Website Template/index.html
  Online Tutorial Website Template/style.css
Labels: Level1, GSSoC22, ready to merge

#345 Added Profile-Tree (Linktree Alternative)
  Profile-Tree (Linktree Alternative)/bg.png
  Profile-Tree (Linktree Alternative)/index.html
  Profile-Tree (Linktree Alternative)/myimg.png
  Profile-Tree (Linktree Alternative)/style.css
Labels: Level2, GSSoC22, ready to merge

#333 Fixed#308 Section 12 on Chinese Restaurant template
  Chinese Restaurant/style.css
Labels: Level1, GSSoC22, ready to merge

#341 Website template for Bootcamp
  Bootcamp Template/img/fundamentals.svg
  Bootcamp Template/img/react.svg
  Bootcamp Template/img/showcase.svg
  Bootcamp Template/index.html
  Bootcamp Template/style.css
Labels: Level2, GSSoC22, ready to merge

#346 Adding the landing page
  Meet Landing Page/images/bottom.jpg
  Meet Landing Page/images/middle1.jpg
  Meet Landing Page/images/middle2.jpg
  Meet Landing Page/images/middle3.jpg
  Meet Landing Page/images/middle4.jpg
  Meet Landing Page/images/potrait1.jpg
  Meet Landing Page/images/potrait10.jpg
  Meet Landing Page/images/potrait11.jpg
  Meet Landing Page/images/potrait12.jpg
  Meet Landing Page/images/potrait2.jpg
  Meet Landing Page/images/potrait3.jpg
  Meet Landing Page/images/potrait4.jpg
  Meet Landing Page/images/potrait5.jpg
  Meet Landing Page/images/potrait6.jpg
  Meet Landing Page/images/potrait7.jpg
  Meet Landing Page/images/potrait8.jpg
  Meet Landing Page/images/potrait9.jpg
  Meet Landing Page/index.html
  Meet Landing Page/styles.css
Labels: Level1, GSSoC22, ready to merge

#336 added Auditions Page
  Auditions_Page/README.md
  Auditions_Page/auditions_page.css
  Auditions_Page/index.html
  Auditions_Page/script.js
Labels: Level1, GSSoC22, ready to merge

#349 Add Food Blog Website
  Food-Blog/css/food.css
  Food-Blog/css/food_responsive.css
  Food-Blog/food page.html
  Food-Blog/freelancing profilePic.jpeg
  Food-Blog/img/096_Ranveer Brar.jpg
  Food-Blog/img/Chef-ranveer-resized-891x1024.jpg
  Food-Blog/img/box1img.jpg
  Food-Blog/img/box2img.jpeg
  Food-Blog/img/box3img.jpeg
  Food-Blog/img/content6977.jpg
  Food-Blog/img/pexels-daria-shevtsova-1095550.jpg
  Food-Blog/img/pexels-photo-1435735 copy.jpeg
  Food-Blog/img/pexels-photo-1435735.jpeg
  Food-Blog/img/pexels-photo-842571.jpeg
  Food-Blog/img/vikas-khanna-bccl.jpg
  Food-Blog/img/wJdHEVJv_400x400.jpg
Labels: Level1, GSSoC22, changes requested

#354 Add a Carousel Landing page template
  Carousel_Landing_Page/assets/css/bootstrap.css
  Carousel_Landing_Page/assets/css/bootstrap.css.map
  Carousel_Landing_Page/assets/css/global_css.css
  Carousel_Landing_Page/assets/css/welcome.css
  Carousel_Landing_Page/assets/media/carousel_0.png
  Carousel_Landing_Page/assets/media/carousel_1.png
  Carousel_Landing_Page/assets/media/carousel_2.png
  Carousel_Landing_Page/assets/media/logo.png
  Carousel_Landing_Page/home.html
  Carousel_Landing_Page/scripts/bootstrap.bundle.js
  Carousel_Landing_Page/scripts/bootstrap.bundle.js.map
  Carousel_Landing_Page/scripts/homepage.js
Labels: Level1

#366 Added travel website template
  Travel website template-1/4861.jpg
  Travel website template-1/Taj-Mahal-Agra-India.jpg
  Travel website template-1/index.html
  Travel website template-1/istock-478831658.jpg
  Travel website template-1/style.css
  style_links.json
Labels: Level1

#348 PortFolio Animated Template
  PortFolio Template/assets/css/bootstrap.min.css
  PortFolio Template/assets/css/fontawesome.min.css
  PortFolio Template/assets/css/icofont.min.css
  PortFolio Template/assets/css/style.css
  PortFolio Template/assets/img/abt.png
  PortFolio Template/assets/img/circuit.png
  PortFolio Template/assets/img/copywriter.png
  PortFolio Template/assets/img/lady.gif
  PortFolio Template/assets/img/portfolio.png
  PortFolio Template/assets/img/programming.png
  PortFolio Template/assets/img/promo.png
  PortFolio Template/assets/js/bootstrap.min.js
  PortFolio Template/assets/js/fontawesome.min.js
  PortFolio Template/index.html
Labels: Level2, GSSoC22, changes requested

#330 Enhance header,body and footer section
  Technology Page/index.html
  Technology Page/style.css
Labels: Level2, GSSoC22

#324 Added Blogger's template
  Bloggers template/Human.png
  Bloggers template/My Desert Safari.html
  Bloggers template/Screenshot_20220303-190732_Instagram.jpg
  Bloggers template/bloggerpreview.png
  Bloggers template/desert collage .png
  Bloggers template/desertsafari.png
  Bloggers template/index.html
  Bloggers template/main.css
  My Desert Safari.html
  style_links.json
Labels: Level1, GSSoC22

#364 Added a Restaurant template
  restaurant template/img/about.jpg
  restaurant template/img/event-custom.jpg
  restaurant template/img/events-bg.jpg
  restaurant template/img/gallery/gallery-1.jpg
  restaurant template/img/gallery/gallery-2.jpg
  restaurant template/img/gallery/gallery-3.jpg
  restaurant template/img/gallery/gallery-4.jpg
  restaurant template/img/gallery/gallery-5.jpg
  restaurant template/img/gallery/gallery-6.jpg
  restaurant template/img/gallery/gallery-7.jpg
  restaurant template/img/gallery/gallery-8.jpg
  restaurant template/img/slide/slide-1.jpg
  restaurant template/img/slide/slide-2.jpg
  restaurant template/img/slide/slide-3.jpg
  restaurant template/index.html
  restaurant template/style.css
Labels: Level3, GSSoC22, ready to merge

#370 Added Github Clone files
  Github_Homepage_Clone/assets/css/style.css
  Github_Homepage_Clone/assets/media/person.jfif
  Github_Homepage_Clone/index.html
Labels: Level3

#363 Add interior home design template by yashi khare
  Home design/css/style.css
  Home design/images/bedroom2 img.jpg
  Home design/images/house 8.jpg
  Home design/images/luxura logo.PNG
  Home design/images/pic10.jpg
  Home design/images/pic11.jpg
  Home design/images/pic17.jpg
  Home design/images/pic18.jpg
  Home design/images/pic19.jpg
  Home design/images/pic22.jpg
  Home design/images/pic23.jpg
  Home design/images/pic24.jpg
  Home design/images/pic25.jpg
  Home design/images/pic26.jpg
  Home design/images/pic6.jpg
  Home design/images/team-img-1.jpg
  Home design/images/team-img-2.jpg
  Home design/images/team-img-3.jpg
  Home design/index.html
  Home design/sass/abstracts/_functions.scss
  Home design/sass/abstracts/_mixins.scss
  Home design/sass/abstracts/_variables.scss
  Home design/sass/base/_animations.scss
  Home design/sass/base/_base.scss
  Home design/sass/base/_typography.scss
  Home design/sass/base/_utilities.scss
  Home design/sass/component/_button.scss
  Home design/sass/component/_composition.scss
  Home design/sass/component/_gallery.scss
  Home design/sass/component/_team.scss
  Home design/sass/layout/_footer.scss
  Home design/sass/layout/_grid.scss
  Home design/sass/layout/_header.scss
  Home design/sass/layout/_navigation.scss
  Home design/sass/main.scss
  Home design/sass/pages/_home.scss
Labels: Level2, GSSoC22, ready to merge

#391 Added the Price Template
  Price/price.css
  Price/price.html
  style_links.json
Labels: Level1, GSSoC22, ready to merge

#376 Improved design of website.
  Food Ordering/img/toplogo.jpg
  Food Ordering/index.html
  Food Ordering/phone.css
  Food Ordering/style.css
Labels: Level2, GSSoC22, ready to merge

#395 Modified the Chinese Restaurant Template
  Chinese Restaurant/index.html
  Chinese Restaurant/style.css
Labels: Level2

#396 College frontEnd webpage #296
  project2/function.js
  project2/img/about.jpg
  project2/img/background.jpg
  project2/img/banner.png
  project2/img/banner2.jpg
  project2/img/basketball.png
  project2/img/cafeteria.png
  project2/img/certificate.jpg
  project2/img/library.png
  project2/img/logo.png
  project2/img/london.png
  project2/img/newyork.png
  project2/img/user1.jpg
  project2/img/user2.jpg
  project2/img/washington.png
  project2/index.html
  project2/style.css
Labels: Level2, GSSoC22, ready to merge

#377 Added responsive Landing page with dark and light theme also with hamburger menu
  light-dark-LandingPage/JS/script.js
  light-dark-LandingPage/assets/logo.png
  light-dark-LandingPage/assets/person.png
  light-dark-LandingPage/assets/shape.png
  light-dark-LandingPage/index.html
  light-dark-LandingPage/styles/style.css
Labels: Level2, GSSoC22, ready to merge

#397 added new project:Amazon-Clone
  Amazon-Clone/README.md
  Amazon-Clone/firebase-debug.log
  Amazon-Clone/firebase.json
  Amazon-Clone/functions/index.js
  Amazon-Clone/functions/package-lock.json
  Amazon-Clone/functions/package.json
  Amazon-Clone/functions/ui-debug.log
  Amazon-Clone/package-lock.json
  Amazon-Clone/package.json
  Amazon-Clone/public/favicon.ico
  Amazon-Clone/public/index.html
  Amazon-Clone/public/logo192.png
  Amazon-Clone/public/logo512.png
  Amazon-Clone/public/manifest.json
  Amazon-Clone/public/robots.txt
Labels: Level3, GSSoC22, changes requested

#405 Updated Responsiveness
  restaurant template/index.html
  restaurant template/style.css
Labels: Level2, GSSoC22, ready to merge

#406 Footer - Template
  Footer-Template/assets/css/styles.css
  Footer-Template/index.html
Labels: Level1, GSSoC22

#451 added a footer with different categories
  Welcome to lucknow/index.html
Labels: Level2, GSSoC22, ready to merge

#455 #387 Fixed Bot Issue : Configuring the automated links
  .github/workflows/greetings.yml
Labels: GSSoC22

#459 Improved gym website template
  gymWebsite/contact.html
  gymWebsite/images/Gym-image-2.jpg
  gymWebsite/images/backimage.jpg
  gymWebsite/images/backimage1.jpg
  gymWebsite/images/ex1.jpg
  gymWebsite/images/gym-image.jpg
  gymWebsite/images/gymm.jpg
  gymWebsite/images/gymw.jpeg
  gymWebsite/images/img3.jpg
  gymWebsite/images/logo.jpg
  gymWebsite/images/logo3.jpg
  gymWebsite/images/pic.jpeg
  gymWebsite/images/pic1.jpeg
  gymWebsite/images/pic2.jpeg
  gymWebsite/images/pic3.jpeg
  gymWebsite/index.html
  gymWebsite/style.css
Labels: Level2

#412 Template for Podcast Website - PsychoPod Website
  Psychopod Website/image/1.png
  Psychopod Website/image/2.png
  Psychopod Website/image/3.png
  Psychopod Website/image/hidden brain.png
  Psychopod Website/image/main.png
  Psychopod Website/image/psych crunch.png
  Psychopod Website/image/psychology unplugged.png
  Psychopod Website/image/shrink rap radio.png
  Psychopod Website/image/therapy chat.png
  Psychopod Website/index.html
  Psychopod Website/preview.png
  Psychopod Website/script.js
  Psychopod Website/style.css
  style_links.json
Labels: GSSoC22, changes requested

#449 Added product landing page
  ProductsLandingPage/landing_page.css
  ProductsLandingPage/landing_page.html
Labels: Level2, GSSoC22

#477 Add mentors
  README.md
Labels: GSSoC22, ready to merge

#474 Fixed issue #394
  Food Ordering/index.html
  Food Ordering/phone.css
  Food Ordering/style.css
Labels: GSSoC22, ready to merge

#476 Added a Template for a Movie Website
  MovieWebsite/README.md
  MovieWebsite/css/style.css
  MovieWebsite/film/edit.css
  MovieWebsite/film/index.html
  MovieWebsite/style.css
Labels: GSSoC22, changes requested

#493 Made the site responsive
  Apple Webiste UI Clone/index.html
  Apple Webiste UI Clone/style.css
Labels: Level2, GSSoC22

#514 fixed broken links and missing images
  script.js
  style_links.json
Labels: Level2

#485 Animated website
  AnimatedFrontendWebsite/edit.css
  AnimatedFrontendWebsite/index.html
  AnimatedFrontendWebsite/main.js
  AnimatedFrontendWebsite/svgs/Browser stats-pana.svg
  AnimatedFrontendWebsite/svgs/Cloud hosting-amico.svg
  AnimatedFrontendWebsite/svgs/Cloud hosting-pana.svg
  AnimatedFrontendWebsite/svgs/Design tools-amico.svg
  AnimatedFrontendWebsite/svgs/Design tools-cuate.svg
  AnimatedFrontendWebsite/svgs/Mobile Marketing-pana.svg
  AnimatedFrontendWebsite/svgs/Mobile apps-cuate.svg
  AnimatedFrontendWebsite/svgs/Web devices-cuate.svg
  AnimatedFrontendWebsite/svgs/Website setup-amico.svg
  AnimatedFrontendWebsite/svgs/Website setup-bro.svg
  AnimatedFrontendWebsite/svgs/Website setup-cuate.svg
  AnimatedFrontendWebsite/svgs/Website setup-pana.svg
  AnimatedFrontendWebsite/wave.png
  style_links.json
Labels: GSSoC22, ready to merge

#501 added images and modified html code
  Technology Page/images/ADB.png
  Technology Page/images/APPLE.jpg
  Technology Page/images/CS.png
  Technology Page/images/MS.jpg
  Technology Page/index.html
Labels: Level1, GSSoC22

#526 Improved and Rectified the Readme
  README.md
Labels: GSSoC22, ready to merge, Level0

#522 Made template responsive and added transition in dialing icon
  Hotel Website/images/background-img-1.jpg
  Hotel Website/images/header4.jpg
  Hotel Website/images/hotelimage.png
  Hotel Website/images/img1.jpg
  Hotel Website/images/img11.jpg
  Hotel Website/images/img2.jpg
  Hotel Website/images/img3.jpg
  Hotel Website/images/img4.jpeg
  Hotel Website/images/img5.jpg
  Hotel Website/images/phone-call.png
  Hotel Website/images/phone.png
  Hotel Website/index.html
  Hotel Website/style.css
  Hotel Website/telephone.png
Labels: GSSoC22, ready to merge
