Repository arpit456jain/Cool-Front-End-Templates, pull requests merged in 2022-05, with the labels that each got.

#724 Added Huddle Landing Page
  Huddle/README.md
  Huddle/images/bg-footer-top-desktop.svg
  Huddle/images/bg-footer-top-mobile.svg
  Huddle/images/bg-section-bottom-desktop-1.svg
  Huddle/images/bg-section-bottom-desktop-2.svg
  Huddle/images/bg-section-bottom-mobile-1.svg
  Huddle/images/bg-section-bottom-mobile-2.svg
  Huddle/images/bg-section-top-desktop-1.svg
  Huddle/images/bg-section-top-desktop-2.svg
  Huddle/images/bg-section-top-mobile-1.svg
  Huddle/images/bg-section-top-mobile-2.svg
  Huddle/images/favicon-32x32.png
  Huddle/images/icon-communities.svg
  Huddle/images/icon-email.svg
  Huddle/images/icon-messages.svg
  Huddle/images/icon-phone.svg
  Huddle/images/illustration-flowing-conversation.svg
  Huddle/images/illustration-grow-together.svg
  Huddle/images/illustration-your-users.svg
  Huddle/images/logo.svg
  Huddle/images/screen-mockups.svg
  Huddle/index.html
  Huddle/script.js
  Huddle/styles.css
  style_links.json
Labels: Level2, GSSoC22, ready to merge

#719 Dark theme responsive cafe webpage
  Dark Theme Responsive Cafe Website/css/style.css
  Dark Theme Responsive Cafe Website/images/about-img.jpeg
  Dark Theme Responsive Cafe Website/images/blog-1.jpeg
  Dark Theme Responsive Cafe Website/images/blog-2.jpeg
  Dark Theme Responsive Cafe Website/images/blog-3.jpeg
  Dark Theme Responsive Cafe Website/images/cart-item-1.png
  Dark Theme Responsive Cafe Website/images/cart-item-2.png
  Dark Theme Responsive Cafe Website/images/cart-item-3.png
  Dark Theme Responsive Cafe Website/images/cart-item-4.png
  Dark Theme Responsive Cafe Website/images/home-img.jpeg
  Dark Theme Responsive Cafe Website/images/logo1.png
  Dark Theme Responsive Cafe Website/images/menu-1.png
  Dark Theme Responsive Cafe Website/images/menu-2.png
  Dark Theme Responsive Cafe Website/images/menu-3.png
  Dark Theme Responsive Cafe Website/images/menu-4.png
  Dark Theme Responsive Cafe Website/images/menu-5.png
  Dark Theme Responsive Cafe Website/images/menu-6.png
  Dark Theme Responsive Cafe Website/images/pic-1.png
  Dark Theme Responsive Cafe Website/images/pic-2.png
  Dark Theme Responsive Cafe Website/images/pic-3.png
  Dark Theme Responsive Cafe Website/images/product-1.png
  Dark Theme Responsive Cafe Website/images/product-2.png
  Dark Theme Responsive Cafe Website/images/product-3.png
  Dark Theme Responsive Cafe Website/images/product-4.png
  Dark Theme Responsive Cafe Website/images/quote-img.png
  Dark Theme Responsive Cafe Website/index.html
  Dark Theme Responsive Cafe Website/js/script.js
Labels: Level3, GSSoC22, ready to merge

#726 Added Clone Of the Website " Go Daddy "
  Go Daddy Website Clone/GoDaddy _ Buy Domain Names_files/DarkWA-092020.svg
  Go Daddy Website Clone/GoDaddy _ Buy Domain Names_files/GD_Guides_ColorLogo.svg
  Go Daddy Website Clone/GoDaddy _ Buy Domain Names_files/GoDaddyGuidesLogo.svg
  Go Daddy Website Clone/GoDaddy _ Buy Domain Names_files/care-arrow.svg
  Go Daddy Website Clone/GoDaddy _ Buy Domain Names_files/chat-baloon.svg
  Go Daddy Website Clone/GoDaddy _ Buy Domain Names_files/en-img-brand-lander-professional-email.jpg
  Go Daddy Website Clone/GoDaddy _ Buy Domain Names_files/en-img-brand-lander-web-hosting.jpg
  Go Daddy Website Clone/GoDaddy _ Buy Domain Names_files/spinner.svg
  Go Daddy Website Clone/index.html
  Go Daddy Website Clone/readme.md
Labels: GSSoC22, ready to merge

#728 Added Start page Website Clone
  Start Page Clone/Startpage - Private Search Engine. No Tracking. No Search History._files/browse-anonymously.svg
  Start Page Clone/Startpage - Private Search Engine. No Tracking. No Search History._files/encrypted-connection.svg
  Start Page Clone/Startpage - Private Search Engine. No Tracking. No Search History._files/girl-on-browser.svg
  Start Page Clone/Startpage - Private Search Engine. No Tracking. No Search History._files/head-edward-snowden.jpg
  Start Page Clone/Startpage - Private Search Engine. No Tracking. No Search History._files/head-laura-brandimarte.jpg
  Start Page Clone/Startpage - Private Search Engine. No Tracking. No Search History._files/head-max-schrems.jpg
  Start Page Clone/Startpage - Private Search Engine. No Tracking. No Search History._files/man-in-laptop.svg
  Start Page Clone/Startpage - Private Search Engine. No Tracking. No Search History._files/map-desktop.svg
  Start Page Clone/Startpage - Private Search Engine. No Tracking. No Search History._files/news-bloomberg.svg
  Start Page Clone/Startpage - Private Search Engine. No Tracking. No Search History._files/news-fast-company.svg
  Start Page Clone/Startpage - Private Search Engine. No Tracking. No Search History._files/news-new-york-times.svg
  Start Page Clone/Startpage - Private Search Engine. No Tracking. No Search History._files/news-techradar.svg
  Start Page Clone/Startpage - Private Search Engine. No Tracking. No Search History._files/news-zdnet-dark.svg
  Start Page Clone/Startpage - Private Search Engine. No Tracking. No Search History._files/online-profiling.svg
  Start Page Clone/Startpage - Private Search Engine. No Tracking. No Search History._files/price-trackers.svg
  Start Page Clone/Startpage - Private Search Engine. No Tracking. No Search History._files/retargeting-ads.svg
  Start Page Clone/Startpage - Private Search Engine. No Tracking. No Search History._files/unprofiled-news.svg
  Start Page Clone/index.html
  Start Page Clone/readme.md
Labels: Level3, GSSoC22, ready to merge

#753 Added Clipboard Landing Page
  Clipboard_Landing_Page/README.md
  Clipboard_Landing_Page/css/master.css
  Clipboard_Landing_Page/images/bg-header-desktop.png
  Clipboard_Landing_Page/images/bg-header-mobile.png
  Clipboard_Landing_Page/images/favicon-32x32.png
  Clipboard_Landing_Page/images/icon-blacklist.svg
  Clipboard_Landing_Page/images/icon-facebook.svg
  Clipboard_Landing_Page/images/icon-instagram.svg
  Clipboard_Landing_Page/images/icon-preview.svg
  Clipboard_Landing_Page/images/icon-text.svg
  Clipboard_Landing_Page/images/icon-twitter.svg
  Clipboard_Landing_Page/images/image-computer.png
  Clipboard_Landing_Page/images/image-devices.png
  Clipboard_Landing_Page/images/logo-google.png
  Clipboard_Landing_Page/images/logo-hp.png
  Clipboard_Landing_Page/images/logo-ibm.png
  Clipboard_Landing_Page/images/logo-microsoft.png
  Clipboard_Landing_Page/images/logo-vector-graphics.png
  Clipboard_Landing_Page/images/logo.svg
  Clipboard_Landing_Page/index.html
  style_links.json
Labels: Level1, GSSoC22, ready to merge

#739 Thanking SVG page
  Thanking SVG page/README.md
  Thanking SVG page/index.html
  style_links.json
Labels: Level1, GSSoC22, ready to merge

#769 Added chrome extension UI (App blocker app)
  Chrome Extension Project/CSS/index.css
  Chrome Extension Project/JS/index.js
  Chrome Extension Project/Other icons/A_logo.png
  Chrome Extension Project/Other icons/setting_icon.png
  Chrome Extension Project/icons/.DS_Store
  Chrome Extension Project/icons/blocks.png
  Chrome Extension Project/icons/facebook@256px-1.png
  Chrome Extension Project/icons/facebook@256px.png
  Chrome Extension Project/icons/facebook@512px-1.png
  Chrome Extension Project/icons/facebook@512px.png
  Chrome Extension Project/icons/feedback.png
  Chrome Extension Project/icons/instagram@256px-1.png
  Chrome Extension Project/icons/instagram@256px.png
  Chrome Extension Project/icons/instagram@512px-1.png
  Chrome Extension Project/icons/instagram@512px.png
  Chrome Extension Project/icons/linkedin@256px-1.png
  Chrome Extension Project/icons/linkedin@256px.png
  Chrome Extension Project/icons/linkedin@512px-1.png
  Chrome Extension Project/icons/linkedin@512px.png
  Chrome Extension Project/icons/redit@256px-1.png
  Chrome Extension Project/icons/redit@256px.png
  Chrome Extension Project/icons/redit@512px-1.png
  Chrome Extension Project/icons/redit@512px.png
  Chrome Extension Project/icons/tik_tok@256px-1.png
  Chrome Extension Project/icons/tik_tok@256px.png
  Chrome Extension Project/icons/tik_tok@512px-1.png
  Chrome Extension Project/icons/tik_tok@512px.png
  Chrome Extension Project/icons/timetable.png
  Chrome Extension Project/icons/twitter@256px-1.png
  Chrome Extension Project/icons/twitter@256px.png
  Chrome Extension Project/icons/twitter@512px-1.png
  Chrome Extension Project/icons/twitter@512px.png
  Chrome Extension Project/icons/youtube@256px-1.png
  Chrome Extension Project/icons/youtube@256px.png
  Chrome Extension Project/icons/youtube@512px-1.png
  Chrome Extension Project/icons/youtube@512px.png
  Chrome Extension Project/index.html
  Chrome Extension Project/manifest.json
  style_links.json
Labels: GSSoC22, ready to merge

#743 Medicare
  Medical Insurance/index.html
  Medical Insurance/script.js
  Medical Insurance/style.css
  Medical Insurance/svg.svg
  style_links.json
Labels: Level1, GSSoC22, ready to merge

#744 Adding the Ui of Discord
  Discord Clone/index.html
  Discord Clone/styles.css
  style_links.json
Labels: Level2, GSSoC22, ready to merge

#775 Reward Points Mobile
  Reward Point/index.html
  Reward Point/preview.jpg
  Reward Point/script.js
  Reward Point/style.css
  style_links.json
Labels: Level1, GSSoC22, ready to merge

#757 Cart Menu
  Cart Menu/index.html
  Cart Menu/style.css
  style_links.json
Labels: Level2, GSSoC22, ready to merge

#734 NeonScience clone
  NeonScience Clone/NEON _ Explore Data Products_files/atmosphere.c3e3b9ad.svg
  NeonScience Clone/NEON _ Explore Data Products_files/biogeochemistry.444f14a2.svg
  NeonScience Clone/NEON _ Explore Data Products_files/ecohydrology.9543995c.svg
  NeonScience Clone/NEON _ Explore Data Products_files/landcover.720f936d.svg
  NeonScience Clone/NEON _ Explore Data Products_files/logo.png
  NeonScience Clone/NEON _ Explore Data Products_files/neon-white-logo.svg
  NeonScience Clone/NEON _ Explore Data Products_files/organisms.f30d435d.svg
  NeonScience Clone/index.html
  NeonScience Clone/readme.md
  style_links.json
Labels: GSSoC22, changes requested

#760 Added Testimonials
  Testimonial/README.md
  Testimonial/images/favicon-32x32.png
  Testimonial/images/icon-next.svg
  Testimonial/images/icon-prev.svg
  Testimonial/images/image-john.jpg
  Testimonial/images/image-tanya.jpg
  Testimonial/images/pattern-bg.svg
  Testimonial/images/pattern-curve.svg
  Testimonial/images/pattern-quotes.svg
  Testimonial/index.html
  Testimonial/script.js
  Testimonial/styles.css
  style_links.json
Labels: GSSoC22, ready to merge

#772 Nestle Nutrition Clone
  Nestle Nutrition Clone/index.html
  Nestle Nutrition Clone/style.css
  style_links.json
Labels: Level1, GSSoC22, changes requested, ready to merge

#780 Market Share
  Market Share Graph/index.html
  Market Share Graph/preview1.jpg
  Market Share Graph/style.css
  style_links.json
Labels: Level1, GSSoC22, ready to merge

#708 Added Google forms Website Clone
  Google Forms Clone/Google Forms.html
  Google Forms Clone/Google Forms_files/134dbGrMBrHFEfdPk5UpsZWEBZb7xJrOKRdESE58Fvcg_400.png
  Google Forms Clone/Google Forms_files/1JL1V2sZIk-u2mwdVzA9-6Br6uwpeS_kYTOJ4kT2vm5c_400.png
  Google Forms Clone/Google Forms_files/1KLcJA1XayB1ZYpuFv_j8tI6nipUsNAxmpgZi0WPjy5w_400.png
  Google Forms Clone/Google Forms_files/1LAKM7lOuNtQrti2Au5o7Ivl0yoKLsNdviuCPAU_Hal0_400.png
  Google Forms Clone/Google Forms_files/1TwEubR7or-QDmeRizrSGlN_PzEF1SnSyjRTaAlbZS_I_400.png
  Google Forms Clone/Google Forms_files/1UVhkBVmAkfnUIhs4YWgogqvfIo5epk6WwOglu7F4gPc_400.png
  Google Forms Clone/Google Forms_files/1ZiZIBxh9ew0W1v8oMTLQ5WLyftAn7SFAN33m5g8pRkk_400.png
  Google Forms Clone/Google Forms_files/1hvwfpXJKhGovi1zf8KXToNiODkPSguY5Yp1Q-IzC7BM_400.png
  Google Forms Clone/Google Forms_files/1kESD6FYaiNyyizpJM63tO4WYjd55SXxxT1ecLzkaM5I_400_1.png
  Google Forms Clone/Google Forms_files/1kkUjv3G7-PgOEUPMTiKvKResxGxS7MTsy5Amj4b0Trw_400.png
  Google Forms Clone/Google Forms_files/1m0UYQl1LSGxl3sGsh9_xjim4hUYQ8BO_zbvcFXv1Qug_400.png
  Google Forms Clone/Google Forms_files/1nb40gzXCRawGODohIlHmYy6dNiZ-CdCOM17Y4Wbrj1U_400_1.png
  Google Forms Clone/Google Forms_files/1pM0fD5FWTXCGw4h0g1WSP8Nj3mS56l1EaCZAec-p2uc_400.png
  Google Forms Clone/Google Forms_files/1qM4zi7nsye17BXrgbbzHlCcHtBWVtxW96WcnJ7as7Qk_400.png
  Google Forms Clone/Google Forms_files/1rHrVyU2AksZ7N1MuPPK5yCH-LkYAirgj23br1hngvzI_400_1.png
  Google Forms Clone/Google Forms_files/1uLvCUYCyLLwxQrjQZ5AP1iN5QCs3pF1m0o71fjY9tic_400_1.png
  Google Forms Clone/Google Forms_files/1xQF3s6EP0d58H-XJ7R440OpREKo4KqEapa0mkw43RPE_400.png
  Google Forms Clone/Google Forms_files/css1.css
  Google Forms Clone/Google Forms_files/forms-blank-googlecolors.png
  Google Forms Clone/Google Forms_files/forms_2020q4_48dp.png
  Google Forms Clone/Google Forms_files/unnamed.png
  Google Forms Clone/readme
  style_links.json
Labels: GSSoC22, changes requested

#767 Added a Coffee Website
  coffee website/css/style.css
  coffee website/images/Screenshot (222).png
  coffee website/images/Screenshot (223).png
  coffee website/images/Screenshot (224).png
  coffee website/images/Screenshot (225).png
  coffee website/images/about-img.jpeg
  coffee website/images/blog-1.jpeg
  coffee website/images/blog-2.jpeg
  coffee website/images/blog-3.jpeg
  coffee website/images/cart-item-1.png
  coffee website/images/cart-item-2.png
  coffee website/images/cart-item-3.png
  coffee website/images/cart-item-4.png
  coffee website/images/home-img.jpeg
  coffee website/images/logo.png
  coffee website/images/menu-1.png
  coffee website/images/menu-2.png
  coffee website/images/menu-3.png
  coffee website/images/menu-4.png
  coffee website/images/menu-5.png
  coffee website/images/menu-6.png
  coffee website/images/pic-1.png
  coffee website/images/pic-2.png
  coffee website/images/pic-3.png
  coffee website/images/product-1.png
  coffee website/images/product-2.png
  coffee website/images/product-3.png
  coffee website/images/quote-img.png
  coffee website/index.html
  coffee website/js/script.js
  style_links.json
Labels: Level3, GSSoC22

#794 New Interface For Chinese Restaurant Website
  Chinese Restaurant/img/EXPERIMENT 3.pdf
  Chinese Restaurant/img/chef.svg
  Chinese Restaurant/index.html
  Chinese Restaurant/style.css
Labels: GSSoC22, ready to merge

#812 Added Email Authentication Method
  Login form/index.html
  Login form/welcome.html
Labels: GSSoC22, ready to merge

#822 Adding the school website
  School Website/index.html
  School Website/pages/results.html
  School Website/pages/styles/results.css
  School Website/pages/styles/syllabus.css
  School Website/pages/syllabus.html
  School Website/preview.png
  School Website/styles.css
  style_links.json
Labels: GSSoC22, ready to merge

#824 Added Github Authentication Method
  Login form/index.html
Labels: GSSoC22

#783 recipe website
  Recipe Website/1.webp
  Recipe Website/2.webp
  Recipe Website/index.html
  Recipe Website/preview.jpg
  Recipe Website/style.css
  style_links.json
Labels: GSSoC22, ready to merge

#832 Added Google Auth
  Login form/index.html
Labels: GSSoC22

#817 Added AmazonSlider
  AmazonHomePageSlider/PngItem_4796944.png
  AmazonHomePageSlider/Profile.pdf
  AmazonHomePageSlider/Readme.txt
  AmazonHomePageSlider/arrow_drop_down_white_24dp (1).svg
  AmazonHomePageSlider/index.html
  AmazonHomePageSlider/language_white_24dp.svg
  AmazonHomePageSlider/menu_white_24dp.svg
  AmazonHomePageSlider/pngkey.com-bharathiyar-png-2542390.png
  AmazonHomePageSlider/script.js
  AmazonHomePageSlider/style.css
  AmazonHomePageSlider/transparent-basket-icon-online-icon-social-market-icon-5d9f98dbdab5d4.3019521615707404438958.png
  AmazonHomePageSlider/—Pngtree—search icon_4699282.png
  AmazonHomePageSlider/—Pngtree—the national flag of india_5934004.png
  style_links.json
Labels: GSSoC22, ready to merge

#821 Added Festivals In India
  Festivals In India/collage.jpg
  Festivals In India/deepawali.jpg
  Festivals In India/ganesh.jpeg
  Festivals In India/holi.jpg
  Festivals In India/index.html
  Festivals In India/janmashtmi.jpg
  Festivals In India/styles.css
  style_links.json
Labels: Level2, GSSoC22, ready to merge

#828 Payment Gateway Added
  Payment_Gateway/cardDetail.html
  Payment_Gateway/index.html
  Payment_Gateway/style.css
  Payment_Gateway/upi.html
  Payment_Gateway/wallet.html
  style_links.json
Labels: GSSoC22, ready to merge

#834 Added Technical documentation page.
  Tech-Landing-page/index.html
  Tech-Landing-page/menu.png
  Tech-Landing-page/preview.png
  Tech-Landing-page/style.css
  style_links.json
Labels: Level2, GSSoC22, ready to merge

#849 Local Fast Food Added
  Local Fast Food/index.html
  Local Fast Food/preview.png
  Local Fast Food/resources/css/img/back-customers.jpg
  Local Fast Food/resources/css/img/hero.jpg
  Local Fast Food/resources/css/queries.css
  Local Fast Food/resources/css/style.css
  Local Fast Food/resources/img/1.jpg
  Local Fast Food/resources/img/2.jpg
  Local Fast Food/resources/img/3.jpg
  Local Fast Food/resources/img/4.jpg
  Local Fast Food/resources/img/5.jpg
  Local Fast Food/resources/img/6.jpg
  Local Fast Food/resources/img/7.jpg
  Local Fast Food/resources/img/8.jpg
  Local Fast Food/resources/img/customer-1.jpg
  Local Fast Food/resources/img/customer-2.jpg
  Local Fast Food/resources/img/customer-3.jpg
  Local Fast Food/resources/img/download-app-android.png
  Local Fast Food/resources/img/hero.jpg
  Local Fast Food/resources/img/icon.png
  Local Fast Food/resources/img/table1.jpg
  Local Fast Food/resources/js/script.js
  Local Fast Food/vendors/.DS_Store
  Local Fast Food/vendors/css/Grid.css
  Local Fast Food/vendors/css/animate.css
  Local Fast Food/vendors/css/normalize.css
  Local Fast Food/vendors/js/jquery.waypoints.min.js
  style_links.json
Labels: GSSoC22, ready to merge

#856 Improved Website - Refactored the Images and Broken Sections
  Apple Webiste UI Clone/index.html
  Books_Website_Template/index.html
  Chinese Restaurant/index.html
  ComingSoon/index.html
  Food_Template/index.html
  Gym Website/contact.html
  Gym Website/index.html
  Home design/about.html
  Home design/index.html
  Huddle/index.html
  Instagram Clone Frontend/index.html
  Microsoft-Clone/index.html
  Pizza Corner/index.html
  Pizza Corner/offers.html
  Portfolio/about me.html
  Portfolio/index.html
  Portfolio/portfolio.html
  Portfolio/work sample.html
  Space Agency Template/index.html
  Tourism_Responsive_Website/index.html
  Yoga Template 2/index.html
  ZomatoClone/index.html
  food website template/demo.html
  food website template/index.html
  index.html
  light-dark-LandingPage/index.html
  project2/index.html
  script.js
  style.css
Labels: Level2, Urgent, GSSoC22, ready to merge

#857 Added Dairy website
  DairyProductWebsite/2226370.jpg
  DairyProductWebsite/complain.png
  DairyProductWebsite/correct.png
  DairyProductWebsite/cow.png
  DairyProductWebsite/dairy.png
  DairyProductWebsite/index.html
  DairyProductWebsite/menu-button-of-three-horizontal-lines.png
  DairyProductWebsite/milk.png
  DairyProductWebsite/readme.md.txt
  DairyProductWebsite/script.js
  DairyProductWebsite/star.png
  DairyProductWebsite/style.css
  style_links.json
Labels: Level2, GSSoC22, ready to merge

#860 personal-portfolio-website#844 added
  personal-portfolio-website/about.html
  personal-portfolio-website/contact.html
  personal-portfolio-website/images/bggif.gif
  personal-portfolio-website/images/pic.png
  personal-portfolio-website/index.html
  personal-portfolio-website/preview.png
  personal-portfolio-website/preview/about.png
  personal-portfolio-website/preview/about_responsive.png
  personal-portfolio-website/preview/contact.png
  personal-portfolio-website/preview/contactResponsive.png
  personal-portfolio-website/preview/home.png
  personal-portfolio-website/preview/home_responsive.png
  personal-portfolio-website/preview/services.png
  personal-portfolio-website/preview/services_responsive.png
  personal-portfolio-website/services.html
  personal-portfolio-website/styles/about.css
  personal-portfolio-website/styles/contact.css
  personal-portfolio-website/styles/services.css
  personal-portfolio-website/styles/styles.css
  style_links.json
Labels: Level3, GSSoC22, ready to merge

#868 CV Template added
  CV Template/index.html
  CV Template/preview.png
  CV Template/profile_pic.jpg
  CV Template/style.css
  style_links.json
Labels: Level2, GSSoC22, ready to merge

#869 Added bankist website
  BankistWebsite/img/card-lazy.jpg
  BankistWebsite/img/card.jpg
  BankistWebsite/img/digital-lazy.jpg
  BankistWebsite/img/digital.jpg
  BankistWebsite/img/grow-lazy.jpg
  BankistWebsite/img/grow.jpg
  BankistWebsite/img/hero.png
  BankistWebsite/img/icon.png
  BankistWebsite/img/icons.svg
  BankistWebsite/img/img-1.jpg
  BankistWebsite/img/img-2.jpg
  BankistWebsite/img/img-3.jpg
  BankistWebsite/img/img-4.jpg
  BankistWebsite/img/logo.png
  BankistWebsite/img/user-1.jpg
  BankistWebsite/img/user-2.jpg
  BankistWebsite/img/user-3.jpg
  BankistWebsite/index.html
  BankistWebsite/readme.md.txt
  BankistWebsite/script.js
  BankistWebsite/style.css
  style_links.json
Labels: GSSoC22, ready to merge

#878 added Pizza rest New Interface
  Pizza Corner/img/bg.png
  Pizza Corner/img/logo.png
  Pizza Corner/img/logo2.png
  Pizza Corner/img/pizza.png
  Pizza Corner/img/pizza3.jpg
  Pizza Corner/img/pizza4.jpg
  Pizza Corner/img/pizza5.jpg
  Pizza Corner/img/pizza6.jpg
  Pizza Corner/img/pizzabg.png
  Pizza Corner/img/pizzapic1.jpg
  Pizza Corner/index.html
  Pizza Corner/style.css
Labels: question, GSSoC22

#874 Candy Museum
  Candy Museum/img/gumball.png
  Candy Museum/img/hand2.png
  Candy Museum/img/lolli_icon.png
  Candy Museum/img/milk.png
  Candy Museum/img/preview1.png
  Candy Museum/img/preview2.png
  Candy Museum/img/sprinkles.png
  Candy Museum/index.html
  Candy Museum/style.css
  style_links.json
Labels: GSSoC22, ready to merge

#866 Headphone Landing Page
  Headphone-Landing-Page/assets/btn-head.png
  Headphone-Landing-Page/assets/cart.png
  Headphone-Landing-Page/assets/google.png
  Headphone-Landing-Page/assets/head-phone.png
  Headphone-Landing-Page/assets/headphone.png
  Headphone-Landing-Page/assets/play-button.png
  Headphone-Landing-Page/assets/play.png
  Headphone-Landing-Page/index.html
  Headphone-Landing-Page/preview.png
  Headphone-Landing-Page/script.js
  Headphone-Landing-Page/style.css
  style_links.json
Labels: GSSoC22, ready to merge

#870 Added model window
  ModelWindow/index.html
  ModelWindow/readme.md.txt
  style_links.json
Labels: GSSoC22, ready to merge

#875 Readme Update issue #867
  README.md
Labels: GSSoC22, ready to merge, Level0

#862 Adding new template of Profile Card
  Profile Card/img/profilepic.jpeg
  Profile Card/index.html
  Profile Card/preview.png
  Profile Card/style.css
  style_links.json
Labels: Level2, GSSoC22, ready to merge

#882 added New Interface of Pizza corner project
  PizzaCorner_NewInterface/img/1.png
  PizzaCorner_NewInterface/img/10.jpg
  PizzaCorner_NewInterface/img/2.png
  PizzaCorner_NewInterface/img/5.png
  PizzaCorner_NewInterface/img/6.jpg
  PizzaCorner_NewInterface/img/7.jpg
  PizzaCorner_NewInterface/img/8.jpg
  PizzaCorner_NewInterface/img/9.jpg
  PizzaCorner_NewInterface/img/b3.jpg
  PizzaCorner_NewInterface/img/bg.png
  PizzaCorner_NewInterface/img/invite.ics
  PizzaCorner_NewInterface/img/logo.png
  PizzaCorner_NewInterface/img/mushroom.jpg
  PizzaCorner_NewInterface/img/pasta.jpg
  PizzaCorner_NewInterface/img/pic.png
  PizzaCorner_NewInterface/img/pizza.png
  PizzaCorner_NewInterface/img/pizza2.jpg
  PizzaCorner_NewInterface/img/pizza3.jpg
  PizzaCorner_NewInterface/img/pizza4.jpg
  PizzaCorner_NewInterface/img/pizza5.jpg
  PizzaCorner_NewInterface/img/pizza6.jpg
  PizzaCorner_NewInterface/img/pizzabg.png
  PizzaCorner_NewInterface/img/pizzapic1.jpg
  PizzaCorner_NewInterface/img/ser11.jpg
  PizzaCorner_NewInterface/img/ser2.jpg
  PizzaCorner_NewInterface/img/ser3.jpg
  PizzaCorner_NewInterface/img/ser4.png
  PizzaCorner_NewInterface/img/ser5.png
  PizzaCorner_NewInterface/img/ser6.jpg
  PizzaCorner_NewInterface/img/ser7.jpg
  PizzaCorner_NewInterface/img/ser8.jpg
  PizzaCorner_NewInterface/img/ser9.jpg
  PizzaCorner_NewInterface/index.html
  PizzaCorner_NewInterface/offers.html
  PizzaCorner_NewInterface/preview.png
  PizzaCorner_NewInterface/style.css
  style_links.json
Labels: Level3, GSSoC22, ready to merge

#880 Saas landing page
  SAAS landing page/Assets/Checkmark.svg
  SAAS landing page/Assets/Hamburger Menu.svg
  SAAS landing page/Assets/Page Image.png
  SAAS landing page/Assets/Sign Up Image.png
  SAAS landing page/Assets/User Avatar 2.svg
  SAAS landing page/Assets/User Avatar 32.svg
  SAAS landing page/Assets/User Avatar.svg
  SAAS landing page/Assets/allSizes.svg
  SAAS landing page/Assets/code.svg
  SAAS landing page/Assets/hero-Illustration.png
  SAAS landing page/Assets/hide password.svg
  SAAS landing page/Assets/silde2.jpg
  SAAS landing page/Assets/silde3.jpg
  SAAS landing page/Assets/silde4.jpg
  SAAS landing page/Assets/star.svg
  SAAS landing page/Assets/time.svg
  SAAS landing page/JS/main.js
  SAAS landing page/SCSS/_basic.scss
  SAAS landing page/SCSS/_links.scss
  SAAS landing page/SCSS/_mixin.scss
  SAAS landing page/SCSS/_variables.scss
  SAAS landing page/SCSS/custom.css
  SAAS landing page/SCSS/custom.css.map
  SAAS landing page/SCSS/custom.scss
  SAAS landing page/index.html
  SAAS landing page/preview.png
  SAAS landing page/signUp.html
  style_links.json
Labels: GSSoC22, ready to merge

#891 Adding Animated Underlink
  AnimatedUnderLink/BeforeAfter.txt
  AnimatedUnderLink/index.html
  AnimatedUnderLink/preview.png
  AnimatedUnderLink/style.css
  style_links.json
Labels: GSSoC22, ready to merge

#889 Yashashviarora patch 1
  Mobile_Template/anchor.js
  Mobile_Template/anchorstyle.css
  Mobile_Template/anchortag.html
  style_links.json
Labels: GSSoC22, ready to merge

#895 Floor Plans Website
  Floor Plans Website/1.jpg
  Floor Plans Website/2.jpg
  Floor Plans Website/3.jpg
  Floor Plans Website/4.jpg
  Floor Plans Website/5.jpg
  Floor Plans Website/6.jpg
  Floor Plans Website/7.jpg
  Floor Plans Website/index.html
  Floor Plans Website/preview.png
  style_links.json
Labels: GSSoC22, ready to merge

#854 Feat- added banana taranslator template
  Translator Template/images/minion.jpg
  Translator Template/index.html
  Translator Template/preview.png
  Translator Template/script.js
  Translator Template/style.css
  style_links.json
Labels: Level2, GSSoC22

#892 Car manufacturing company
  Car manufacturing company/2019-honda-civic-sedan-1558453497.jpg
  Car manufacturing company/2020_Chevrolet_Corvette_Stingray_3LT_EVOX.jpg
  Car manufacturing company/SONATA-hero-option1-764A5360-edit-640x354.jpg
  Car manufacturing company/Toyota-Glanza-060520221539.jpg
  Car manufacturing company/car-repair-logo-designs-concept-for-company-vector-25721032.jpg
  Car manufacturing company/car-service-company-logo-with-sport-vehicle-vector-19953531.png
  Car manufacturing company/cosySec.png
  Car manufacturing company/download.jpg
  Car manufacturing company/index.html
  Car manufacturing company/josh-berquist-_4sWbzH5fp8-unsplash.jpg
  Car manufacturing company/oakley-design-lamborghini-aventador-lp760-4-dragon-edition-08.jpg
  style_links.json
Labels: Level2, GSSoC22, ready to merge

#903 Updated Main website (Template error)
  style_links.json
Labels: Level1, GSSoC22
